# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  push:
  pull_request:
jobs:
  push:
    if: github.event_name == 'push'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - run: echo "hello user"
  after_push:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a post push check. Only succeeds when push succeeds"
  on_pull:
    if: github.event_name == 'pull_request'
    runs-on: 'ubuntu-latest'
    steps:
      - run: echo "Triggered by a PR"
  artifact_1:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOF > output.txt
          Hello from CI
          Generated on runner
          EOF
      - uses: actions/upload-artifact@v4
        with:
          name: art1
          path: output.txt
    
