# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  push:
  pull_request:
jobs:
  push:
    if: github.events.name == 'push'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - run: echo "hello user"
  on_pull:
    if: github.events.name == 'pull_request'
    runs-on: 'ubuntu-latest'
    steps:
      - run: echo "Triggered by a PR"

